name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Fixes"
    labels:
      - "bug"
  - title: "🧹 Maintenance"
    labels:
      - "chore"
      - "ci"

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

template: |
  ## ✨ Changes

  $CHANGES

  ---
  🕐 Generated on $DATE
