name: CI Lazarus
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build package
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: gcarreno/setup-lazarus@v3.3.1
      with:
        lazarus-version: "dist"
    - run: lazbuild Duhamel_integral.lpi
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: package
        path: Duhamel_integral.exe
        retention-days: 5
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: Duhamel_integral.exe
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
