# This is a basic workflow to help you get started with Actions

name: CI Lazarus

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build package
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: gcarreno/setup-lazarus@v3.0.2
      with:
        lazarus-version: "dist"
    - run: lazbuild Duhamel_integral.lpi
       
  release:
  
    name: Publish release
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: package
            path: Duhamel_integral.exe
            retention-days: 5
            
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: Duhamel_integral.exe
